# TCL File Generated by Component Editor 12.1sp1
# Sun Mar 01 14:46:54 MST 2015
# DO NOT MODIFY


# 
# frequencyDivider "frequencyDivider" v1.0
# null 2015.03.01.14:46:54
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module frequencyDivider
# 
set_module_property NAME frequencyDivider
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME frequencyDivider
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL frequencyDivider
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file frequencyDivider.vhd VHDL PATH frequencyDivider.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_out
# 
add_interface clock_out clock start
set_interface_property clock_out associatedDirectClock ""
set_interface_property clock_out clockRate 0
set_interface_property clock_out clockRateKnown false
set_interface_property clock_out ENABLED true

add_interface_port clock_out clk31250Hz clk Output 1


# 
# connection point clock_in
# 
add_interface clock_in clock end
set_interface_property clock_in clockRate 0
set_interface_property clock_in ENABLED true

add_interface_port clock_in clk50MHz clk Input 1

